services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html/api
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_USER:
      DB_PASS:
      DB_NAME:
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: IFA_2026
      MYSQL_USER: ifa2026
      MYSQL_PASSWORD: brightb8462@
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
