CREATE TABLE `USER` (
    `ID` varchar(255) NOT NULL,
    `USER_NM` varchar(255) DEFAULT NULL,
    `USER_EMAIL` varchar(255) DEFAULT NULL,
    `USER_GENDER` varchar(50) DEFAULT NULL,
    `USER_AGE` varchar(255) DEFAULT NULL,
    `USER_REWARD` tinyint(1) DEFAULT NULL COMMENT '리워드 수령 여부',
    `DEVICE_ID` varchar(255) DEFAULT NULL COMMENT '기기 UUID',
    `CHECKIN_DATE` date DEFAULT NULL COMMENT '체크인 날짜',
    `CREATE_DT` timestamp NULL DEFAULT NULL,
    `UPDATE_DT` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_DEVICE_DATE` (`DEVICE_ID`,`CHECKIN_DATE`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='체크인 현황';

CREATE TABLE IF NOT EXISTS `SURVEY` (
    ID         INT AUTO_INCREMENT NOT NULL,
    USER_ID    VARCHAR(255)  NOT NULL COMMENT '회원 코드(USER.ID)',
    Q1         VARCHAR(255) NULL COMMENT '단일선택 텍스트',
    Q2         VARCHAR(255) NULL COMMENT '단일선택 텍스트',
    Q3         JSON         NULL COMMENT '멀티선택 텍스트 배열',
    Q4         JSON         NULL COMMENT '멀티선택 텍스트 배열',
    Q5         TEXT         NULL COMMENT '자유서술',
    REWARD     TINYINT(1)   DEFAULT 0 COMMENT '서베이 리워드 여부',
    CREATE_DT  DATETIME     NULL,
    UPDATE_DT  DATETIME     NULL,
    CONSTRAINT SURVEY_PK PRIMARY KEY (ID),
    UNIQUE KEY UK_USER (USER_ID),
    CONSTRAINT `SURVEY_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='설문 현황';

CREATE TABLE IF NOT EXISTS `EX_DATA` (
    `ID` int NOT NULL AUTO_INCREMENT,
    `USER_ID` varchar(255) DEFAULT NULL COMMENT '회원 코드',
    `ZONE` varchar(255) DEFAULT NULL COMMENT '체험 공간',
    `SITUATION` varchar(255) DEFAULT NULL COMMENT '상황',
    `SITUATION_DESC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '상황 설명',
    `QR_SCANNED` tinyint(1) DEFAULT '0' COMMENT 'QR 스캔 여부',
    `CREATE_DT` datetime DEFAULT NULL COMMENT '생성일자',
    `UPDATE_DT` datetime DEFAULT NULL COMMENT '수정 일자',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `EX_DATA_UNIQUE` (`ZONE`,`USER_ID`),
    KEY `EX_DATA_USER_FK` (`USER_ID`),
    CONSTRAINT `EX_DATA_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='체험 현황';


CREATE TABLE IF NOT EXISTS `PERSONA` (
    `ID` int NOT NULL AUTO_INCREMENT,
    `USER_ID` varchar(255) NOT NULL COMMENT '회원 코드(USER.ID)',
    `PERSONA` varchar(255) NOT NULL COMMENT '페르소나',
    `PERSONA_CODE` varchar(255) NOT NULL COMMENT '페르소나 코드',
    `REASON` varchar(255) NOT NULL COMMENT '페르소나 선택이유',
    PRIMARY KEY (`ID`),
    KEY `PERSONA_USER_FK` (`USER_ID`),
    CONSTRAINT `PERSONA_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='페르소나 현황';

CREATE TABLE IF NOT EXISTS `SYSTEM_LOG` (
`ID` int NOT NULL AUTO_INCREMENT,
`TARGET_ID` varchar(255) DEFAULT NULL COMMENT '타겟 코드',
`USER_ID` varchar(255) DEFAULT NULL COMMENT '회원 코드',
`CREATE_DT` datetime DEFAULT NULL COMMENT '생성일자',
PRIMARY KEY (`ID`),
UNIQUE KEY `SYSTEM_LOG_UNIQUE` (`USER_ID`,`CREATE_DT`),
CONSTRAINT `SYSTEM_LOG_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='로그 테이블';
