CREATE TABLE IF NOT EXISTS `USER`  (
    `ID` varchar(255)  NOT NULL,
    `USER_NM` varchar(255)  DEFAULT NULL,
    `USER_EMAIL` varchar(255)  DEFAULT NULL,
    `USER_GENDER` varchar(50)  DEFAULT NULL,
    `USER_AGE` varchar(255)  DEFAULT NULL,
    `USER_FAMILY` varchar(255)  DEFAULT NULL,
    `USER_PS` varchar(255) DEFAULT NULL COMMENT '페르소나',
    `DEVICE_ID` varchar(255) DEFAULT NULL COMMENT '기기 식별 UUID',
    `CHECKIN_DATE` date DEFAULT NULL COMMENT '체크인 날짜(KST)',
    `CREATE_DT` timestamp NULL DEFAULT NULL,
    `UPDATE_DT` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_DEVICE_DATE` (`DEVICE_ID`,`CHECKIN_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
