CREATE TABLE IF NOT EXISTS `USER`  (
    `ID` varchar(255)  NOT NULL,
    `USER_NM` varchar(255)  DEFAULT NULL,
    `USER_EMAIL` varchar(255)  DEFAULT NULL,
    `USER_GENDER` varchar(50)  DEFAULT NULL,
    `USER_AGE` varchar(255)  DEFAULT NULL,
    `USER_FAMILY` varchar(255)  DEFAULT NULL,
    `USER_PS` varchar(255) DEFAULT NULL COMMENT '페르소나',
    `DEVICE_ID` varchar(255) DEFAULT NULL COMMENT '기기 식별 UUID',
    `CHECKIN_DATE` date DEFAULT NULL COMMENT '체크인 날짜(KST)',
    `CREATE_DT` timestamp NULL DEFAULT NULL,
    `UPDATE_DT` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_DEVICE_DATE` (`DEVICE_ID`,`CHECKIN_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `REWARD` (
  `USER_ID` varchar(255)   DEFAULT NULL,
  `ID` varchar(255)  NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REWARD_USER_FK` (`USER_ID`), CONSTRAINT `REWARD_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
